name: coolapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # UI / Animations already used in your project
  animated_splash_screen: ^1.3.0
  animated_text_kit: ^4.2.2
  page_transition: ^2.2.1
  marquee: ^2.3.0
  audioplayers: ^6.5.1

  # Location + permissions (already used)
  geolocator: ^14.0.2
  permission_handler: ^12.0.1

  # NEW â†’ required to call Python backend /route
  http: ^1.1.0

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/maps.jpeg
    - assets/logo.png
    - assets/finalmap.png
    - assets/finalnav.png
    - assets/splash_sound.mp3